// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxJc0DegBvHb5a_XuOdxv2gLIDyb6LTII',
    appId: '1:1023081342727:web:b4d3822836b3c6ac29c7a2',
    messagingSenderId: '1023081342727',
    projectId: 'mytrend-zen',
    authDomain: 'mytrend-zen.firebaseapp.com',
    storageBucket: 'mytrend-zen.firebasestorage.app',
    measurementId: 'G-4H72WZQM9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjRBFy-eMs6v0Mt0WTBF2vAZG37EhFKVc',
    appId: '1:1023081342727:android:8feea6528c267ae229c7a2',
    messagingSenderId: '1023081342727',
    projectId: 'mytrend-zen',
    storageBucket: 'mytrend-zen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD8xKqopHBoqQXAbgt4IQayotib_PsVwE',
    appId: '1:1023081342727:ios:d5a6acbe3eb2e0ea29c7a2',
    messagingSenderId: '1023081342727',
    projectId: 'mytrend-zen',
    storageBucket: 'mytrend-zen.firebasestorage.app',
    androidClientId: '1023081342727-p567m4cukinlv3j1c0953hatvdnhv3as.apps.googleusercontent.com',
    iosClientId: '1023081342727-4prn68peo3fcadcvm1t3jck86pmncnf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.trendZen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD8xKqopHBoqQXAbgt4IQayotib_PsVwE',
    appId: '1:1023081342727:ios:d5a6acbe3eb2e0ea29c7a2',
    messagingSenderId: '1023081342727',
    projectId: 'mytrend-zen',
    storageBucket: 'mytrend-zen.firebasestorage.app',
    androidClientId: '1023081342727-p567m4cukinlv3j1c0953hatvdnhv3as.apps.googleusercontent.com',
    iosClientId: '1023081342727-4prn68peo3fcadcvm1t3jck86pmncnf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.trendZen',
  );
}
